# Generated by Django 5.1.4 on 2024-12-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('digit', models.IntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
