# Generated by Django 5.1.4 on 2024-12-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='predict',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
